server:
  port: 8080
  mode: debug

jwt:
  secret: dev-secret-key-change-in-production
  expire_hours: 168

database:
  driver: sqlite
  path: ./data/illust-nest.db

storage:
  main: mylocal
  backup: ""
  backup_mode: mirror
  providers:
    - name: mylocal
      type: local
      upload_base_dir: ./data/uploads
    - name: minio
      type: s3
      endpoint: "127.0.0.1:9000"
      region: ""
      bucket: "default"
      access_key_id: "ciLxPtTB8P2RY3VW"
      secret_access_key: "Xweuc4oDnpijOpn6Kvk1lp9E9Hy3c2lH"
      use_ssl: false
      force_path_style: false
      prefix: "illust-nest"
    - name: mywebdav
      type: webdav
      webdav_endpoint: "http://localhost:9090/remote.php/dav/files/root"
      webdav_username: "root"
      webdav_password: "abcd1234"
      webdav_prefix: "illust-nest"

web:
  static_dir: ./frontend/dist
  embed: false
